# Generated by Django 5.0.2 on 2024-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloans',
            fields=[
                ('Loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Loan_amt', models.IntegerField()),
                ('Mail_id', models.CharField(max_length=30)),
                ('Account_no', models.IntegerField()),
            ],
        ),
    ]
